FROM node:18-alpine

WORKDIR /app

# Copy package.json first
COPY webapp/package.json ./

# Install dependencies and generate package-lock.json
RUN npm install

# Source
COPY webapp .

# Build
RUN npm run build

# Start
CMD ["npm", "run", "dev"]