FROM node:18-alpine

WORKDIR /app

# Copy package.json first
COPY display/package.json ./

# Install dependencies and generate package-lock.json
RUN npm install

# Copy TypeScript config
COPY display/tsconfig.json ./

# Source
COPY display/src ./src

# Build
RUN npm run build

# Start
CMD ["npm", "run", "dev"]