version: '3.8'

services:
  # Main Next.js application
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - NEXT_PUBLIC_WS_URL=ws://localhost:3002
    networks:
      - wrale-net
    depends_on:
      - minio
      - websocket-server

  # MinIO for asset storage
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
    networks:
      - wrale-net

  # Display client simulator
  display-client:
    build:
      context: .
      dockerfile: Dockerfile.display
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=ws://localhost:3002
    networks:
      - wrale-net
    depends_on:
      - webapp
      - websocket-server

  # Rust WebSocket server
  websocket-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3002:3001"
    networks:
      - wrale-net

networks:
  wrale-net:
    driver: bridge

volumes:
  minio_data: