FROM node:18-alpine

WORKDIR /app

# Dependencies
COPY display/package.json display/package-lock.json ./
RUN npm ci

# Source
COPY display .

# Build
RUN npm run build

# Start
CMD ["npm", "run", "dev"]